config/routes.rb
Instaprint::Application.routes.draw do

  resources :pages
  resources :feed
  resources :services
  resources :orders
  
  get "help/about"
  get "help/payment"
  get "help/politics"
  get "help/faq"  
	
	# Main index page
  root :to => "Pages#index"
  
  # Connection routes
  match "/connect" , :to => "sessions#connect"
  match "/callback" , :to => "sessions#callback"
  match "/logout" , :to => "sessions#logout"
  
  # Services & products
  match "/services" , :to => "services#index"
  match "/service" , :to => "services#show"
  
  match "/profile" , :to => "feed#profile"
  match "/instafeed" , :to => "feed#index"
  match "/construct" , :to => "constructor#show"
  
  # Orders
  match "/book" , :to => "orders#new"
  match "/book" , :to => "orders#new", :via => :post
  match "/paymethod", :to => "orders#paymethod"
  match "/check/promocode", :to => "promocodes#validate"

  # Payment actions
  match "/payment", :to => "orders#payment"
  
  match "/payment/pagomaster", :to => "payment#pagomaster", :via => :post
  match "/pagomaster/success", :to => "orders#payment"
  match "/pagomaster/fail", :to => "orders#paymenterror"
    
  match "/payment/robox", :to => "payment#robox", :via => :post
  match "/robokassa/success", :to => "orders#payment"
  match "/robokassa/fail", :to => "orders#paymenterror"
      
  # PDF generation
  match "/pdfgen", :to => "orders#pdfgen"

  # Shopping cart
  match "/basket", :to => "orders#paymethod"
  match "/delete", :to => "basket#delete"
  match "/update", :to => "basket#update"

  # Help section
  match "/help/:action", :to => "help#:action"
  
  # Admin routes
  match "/adminka", :to => "admin#index"
  match "/check", :to => "admin#check"
  match "/adlogin", :to => "admin#login"
  match "/adlogout", :to => "admin#logout"
  match "/conds", :to => "admin#conditions"
  match "/track", :to => "admin#track"
  match "/delord", :to => "admin#delete"
  match "/showadmins", :to => "admin#showadmins"
  match "/editadmin", :to => "admin#editadmin"
  match "/createadmin", :to => "admin#createadmin"

  # Promocodes 
  resources :promocodes, :path => "/adminka/promocodes"

  #help
  match "/help/:action", :to => "help#:action"
  match "/contacts", :to => "pages#contacts"

end

app/models/admin.rb
# -*- coding: utf-8 -*-
class Admin < ActiveRecord::Base
  attr_accessible :login, :password
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/models/billing.rb
class Billing < ActiveRecord::Base
  attr_accessible :billing_status, :billingtype, :description, :orders, :totalsum
end

app/models/order.rb
# -*- coding: utf-8 -*-
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :service

  def self.ids
  	dirs = self.select(:direction).uniq
  	ids = []

    i = 0
    while i < dirs.size do
      ids << self.find_by_direction(dirs[i].direction, :limit => 1).direction
      i += 1
    end
    return ids
  end
end

app/models/pricing.rb
# -*- coding: utf-8 -*-
class Pricing < ActiveRecord::Base
	has_many :pricing
end

app/models/promocode.rb
# -*- coding: utf-8 -*-
class Promocode < ActiveRecord::Base

	attr_accessible :code, :status, :user_id, :activation, :bonus, :use_until, :order_id, :service_id
	belongs_to :user
	belongs_to :service
	belongs_to :order

#================Methods======================

#=============================================

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :price_dhl, :price_ems, :price_local, :region
end

app/models/regions.rb
# -*- coding: utf-8 -*-
class Regions < ActiveRecord::Base
	has_many :regions
end

app/models/service.rb
# -*- coding: utf-8 -*-
class Service < ActiveRecord::Base
	has_many :orders
	has_many :promocodes
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
	has_many :orders
	has_many :promocodes
end

app/controllers/feed_controller.rb
# -*- coding: utf-8 -*-
class FeedController < ApplicationController
  def index
    
    @title = "Seleccionar fotos | Instaprinter - Impresión de fotos Instagram" #Тайтл страницы
    
    # Переадресация домой если не выбран сервис и к выбору фоток в противном случае   
    if params[:s] 
      session[:s] = params[:s]  # Запись сервиса в сессию если он есть
    end
        
    #Переадресация если нет ключа
    if (!session[:access_token])and(!session[:s])
       redirect_to root_path
    elsif (!session[:access_token])and(session[:s])
      redirect_to :controller => 'sessions', :action => 'connect'
    else

    #Подключение клиента и выбор данных
    count_per_query = 60
    client = Instagram.client(:access_token => session[:access_token])
    @user = client.user
    user_ids = Instagram.user_search(@user)
    user_id = user_ids.first
    first_query = client.user_recent_media({count: count_per_query})
    max_id = first_query.last.id
   
    
    i = 0
    ret = []
    first_query.each do |fq|
      ret << fq   
    end
    while true do 
      query = client.user_recent_media(user_id, {access_token: session[:access_token], count: count_per_query, max_id: max_id})
      break if query.empty? 
      query.each do |q|
        ret << q  
      end
      max_id = query.last.id
      i += 1
    end

    @recent_media_items = ret
    
    @serv = Service.find(session[:s])
  
    #Генерация бредкрамбсов
    add_breadcrumb "Seleccionar Fotos" , instafeed_path, nil, 'bread'
    
    end
    
  end

  def profile # Unused
    
    redirect_to root_path
        
  end
end

app/controllers/help_controller.rb
# -*- coding: utf-8 -*-
class HelpController < ApplicationController
  def about
  end

  def payment
  end

  def politics
  end

  def faq
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constructor_helper.rb
module ConstructorHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/conditions.html.erb
<table cellspacing="0" cellpadding="0" border="0" width="940">
	<thead>
	<tr>			
		<td width="20"></td>
		<td width="60">Username</td>
		<td width="60">Phone</td>
		<td width="80">Product</td>
		<td width="100">Status of order</td>
		<td width="80">Date of order</td>
		<td width="150">Address</td>
		<td width="100">Delivery</td>
		<td width="20">PDF</td>	
		<td width="150">Track Number</td>	
	</tr>			
	<thead>
	<tbody>
		

	<% @conditions.each do |o|%>
		<tr>
			<td><%= check_box o.id, "on", :id => "#{o.id}", :onblur => "javascript:collectOrders(this.id)" %></td>
			<td>
				<a title="Отправить сообщение пользователю" href="mailto:<%= o.user.email %>"><%= o.user.login %></a><br />
				<em><%= o.user.fname %></em>
				</td>
			<td><%= o.user.phone %></td>
			<td><%= o.service.sname %></td>
			<td><%= o.status %></td>
			<td><%= o.date.strftime("%d.%m.%Y") %></td>
			<td>
			<%= o.direction %>, <%= o.comuna %>, <%= o.city %>, <%= Regions.find_by_id(o.region).region %>
			</td>
			<td><%= o.delivery_type %></td>
			<td><a href="<%= o.pdfref %>"><img src="/images/pdfref.gif"></a></td>				
			<% if !o.tracknum.nil? && !o.tracknum.blank? %>
					<% oid = "#trackform#{o.id}" %>
					<td><%= form_tag "javascript:trackformdo('#{oid}')".html_safe, :id => "trackform#{o.id}" do %>
						<%= text_field_tag("tracknum", "#{o.tracknum}", :disabled => true, :id => "trackfield#{o.id}") %>
						<%= hidden_field_tag "oid", "#{o.id}" %>
						<%= submit_tag "OK", :id => "sb#{o.id}", :disabled => true, :class => "hidden" %>
						<% end %>	
					<a href="javascript:chtrack('<%= o.id %>')"><img src="/images/wand.gif" ></a>	
					</td>
				<% else %>
					<% oid = "#trackform#{o.id}" %>
					<% tfid = "#trackfield#{o.id}" %>
					<td>
						<%= form_tag "javascript:trackformdo('#{oid}')".html_safe, :id => "trackform#{o.id}" do %>
						<%= text_field_tag("tracknum", nil, :id => "trackfield#{o.id}") %>
						<%= hidden_field_tag "oid", "#{o.id}" %>
						<%= submit_tag "OK", :id => "sb#{o.id}", :class => "hidden" %>
						<% end %>
					</td>
				<% end %>
		</tr>
	<% end %>

	</tbody>
</table>

	<%= form_tag "javascript:delOrders()".html_safe, :id => "delform" do %>
		<% @conditions.each do |o| %>
			<%= hidden_field_tag "del[]", "", :id => "del#{o.id}" %> 
		<% end %>
	<% end %>

	<% if @conditions.size > 0 %>
	<p class="center">
		<%= link_to "Delete", "javascript:subdel()" %>
		&nbsp;&nbsp;|&nbsp;&nbsp;
		<%= link_to "Check all", "javascript:selectAllOrders()", :id => "chlink" %>
	</p>
	<% end %>

app/views/admin/editadmin.html.erb

<script type="text/javascript">
  $(document).ready(function(){
    $("#edadminform").validate({
    	debug: true,	
			onfocusout: false,
    	invalidHandler: function(form, validator) {
          var errors = validator.numberOfInvalids();
          if (errors) {
              //alert(validator.errorList[0].message);
							$('#ErrorHandler').html(validator.errorList[0].message);
							$('#ErrorHandler').animate({opacity: '0.8'}, 500);
							$('#ErrorHandler').slideDown("slow").delay(2000).slideUp("slow");
              validator.errorList[0].element.focus();
     	   }
    	},
    	rules: {
    		login: "required",
    		password: "required",
    		confirmation: {
    			equalTo: "#password"}
    	},
    	messages: {
    		login: "Input your login",
    		password: "Tape your password",
    		confirmation: "Invalid confirmation"
    	},
    	errorPlacement: function(error, element) {
		// Override error placement to not show error messages beside elements //
		},
			submitHandler: function(form) { 
				form.submit();
			}
		});	
    });
  });
</script>

<header>		
	<h1><span><%= @stat %> </span>ADMIN</h1>
</header>
<div id="ErrorHandler"></div>
<%= render 'layouts/adlogout' %>

<section id="admincontent" class="commontypo clearfix">
	<section id="breadcrumbs" class="generic">
		<%= render 'layouts/abreadcrumbs' %>
	</section><!--#breadcrumps-->
	
	<h3 class="center"></h3>
	
	<%= form_tag url_for(:controller => "admin", :action => "createadmin"), :method => 'post', :id => 'edadminform' do %>	
	<table cellspacing="0" cellpadding="0" border="0" width="400">
		<thead>
			<tr>
				<td colspan="2">
					Admin management
				</td>
			</tr>
		</thead>
		<tbody>
		<tr>			
			<td width="200"><%= label_tag "Login:" %></td>
			<td width="200"><%= text_field_tag "login", @login %></td>
		</tr>
		<tr>			
			<td width="200"><%= label_tag "Password:" %></td>
			<td width="200"><%= password_field_tag "password", @password, :id => "password" %></td>
		</tr>
		<tr>			
			<td width="200"><%= label_tag "Confirm password:" %></td>
			<td width="200"><%= password_field_tag "confirmation", @password %></td>
		</tr>
		</tbody>
		<tfoot>
		<tr>			
			<td colspan="2">
				<%= hidden_field_tag "aid", params[:aid] %>
				<%= submit_tag @submit %>				
			</td>
		</tr>
		</tfoot>		
		</table>
		<% end %>		
</section>

<script type="text/javascript">
  $(document).ready(function(){
    $("#edadminform").validate({
    		debug: true,	
			onfocusout: false,
    	invalidHandler: function(form, validator) {
          var errors = validator.numberOfInvalids();
          if (errors) {
              //alert(validator.errorList[0].message);
							$('#ErrorHandler').html(validator.errorList[0].message);
							$('#ErrorHandler').animate({opacity: '0.8'}, 500);
							$('#ErrorHandler').slideDown("slow").delay(2000).slideUp("slow");
              validator.errorList[0].element.focus();
     	   }
    	},
    	rules: {
    		login: "required",
    		password: "required",
    		confirmation: {
    			equalTo: "#password"}
    	},
    	messages: {
    		login: "Input your login",
    		password: "Tape your password",
    		confirmation: "Invalid confirmation"
    	},
    	errorPlacement: function(error, element) {
		// Override error placement to not show error messages beside elements //
		},
		submitHandler: function(form) { 
			form.submit();
		}		
    });
  });
</script>

app/views/admin/index.html.erb
<header>		
	<h1><span>INST</span>ADMINKA</h1>
</header>

<%= render 'layouts/adlogout' %>

<section id="admincontent" class="commontypo clearfix">
	
	<section id="conditions">
		<p class="center"><%= link_to "Admins", :action => "showadmins" %></p>
		<p class="center"><%= link_to "Promocodes", promocodes_path %></p>


		<h3 class="center">Define conditions</h3>	

		<%= form_tag("javascript:adminformdo()".html_safe, :id => "adminform") do %>		
		<table cellspacing="0" cellpadding="0" border="0" width="940">
			<thead>
			<tr>				
				<td width="220">Date From</td>
				<td width="220">Date To</td>
				<td width="100">Product Type</td>
				<td width="100">Order Status</td>
				<td width="100">Users</td>
				<td width="100">Actions</td>
			</tr>				
			<thead>
			<tbody>
			<tr>
				<td><%= date_select "start", "post", :order => [:day, :month, :year], 
				:default => 1.month.ago %></td>
				<td><%= date_select "end", "post", :order => [:day, :month, :year] %></td>
				<td><%= select("post", "stype", Service.find(:all).collect {|s| [ s.sname] }, :prompt => "All") %></td>	
				<td><%= select_tag "status", options_for_select(['Recibido', 'Generado', 'Pagado', 'Enviado'], 'Generado'), 
				:prompt => "All" %></td>
				<td><%= select("post", "user", User.find(:all).collect {|u| [ u.login] }, :prompt => "All") %></td>
				<td><%= submit_tag "Apply conditions" %></td>
			</tr>
			</tdoby>
			</table>

			<%= hidden_field_tag "ischecked", "Check all", :id => "chall" %>
		<% end %>

		<p class="center"></p>

	</section><!--#conditions-->

	<div id="tabledata">
		<script type="text/javascript">$('#adminform').submit();</script>
	</div>
</section>

app/views/admin/login.html.erb
<header>		
	<h1>Administration Login</h1>
</header>


<section id="content" class="widecolumn admin clearfix">
	
<%= @em %>

<%= form_tag({:controller => "admin", :action => "check"}, :method => "post", :id => "loginadmin") do%>
	<%= label_tag "Login" %><br>
	<%= text_field_tag "login" %><br>
	<%= label_tag "Password" %><br>
	<%= password_field_tag "password" %><br>
	<%= submit_tag "Login" %>
<% end %>

</section><!--#content-->

app/views/admin/showadmins.html.erb
<header>		
	<h1>CREATE / EDIT ADMINS</h1>
</header>

<%= render 'layouts/adlogout' %>

<section id="admincontent" class="commontypo clearfix">
	<section id="breadcrumbs" class="generic">
		<%= render 'layouts/abreadcrumbs' %>
	</section><!--#breadcrumps-->
	
	<h3 class="center"><%= link_to "New Admin", :action => "editadmin" %></h3>
	
	<table cellspacing="0" cellpadding="0" border="0" width="500">
		<thead>
		<tr>			
			<td width="200">Admin</td>
			<td width="200">Email</td>
			<td width="80">Actions</td>
		</tr>	
		<thead>
		<tbody>
		<% @admins.each do |a| %>			
		<tr>
			<td><%= link_to "#{a.login}", :action => "editadmin", :aid => "#{a.id}" %></td>
			<td>###</td>
			<td>###</td>
		</tr>
		<% end %>
		</tdoby>
		</table>
</section>

app/views/layouts/_abreadcrumbs.html.erb
<% if session[:abread]  %>
	<% bread = session[:abread]%>
	<p>Estas en 
	<% bread[0..-2].each do |txt , path|%>
		<%= link_to txt , path %> ::
	<% end %>
	<%= bread.last.first %></p>
<% end %>

app/views/layouts/_adlogout.erb
<% if session[:admin] %>
<div id="logout">
	<a href=<%= url_for(:controller => "admin", :action => "logout") %> class="awesome medium">Log Out</a>
</div>
<% end %>

app/views/layouts/_breadcrumbs.html.erb
<% if session[:bread]  %>
	<% bread = session[:bread]%>
	<p>Estas en 
	<% bread[0..-2].each do |txt , path|%>
		<%= link_to txt , path %> ::
	<% end %>
	<%= bread.last.first %></p>
<% end %>

app/views/layouts/_logout.html.erb
<% if session[:access_token] %>
<div id="logout">
	<a href="javascript:logout();" class="awesome medium">Terminar sesión</a>
</div>
<% end %>	

app/views/layouts/application.html.erb
<%
# Prepare href link 
# If not logged yet send user to Instagram Auth page
if !session[:access_token]
	loginlink = url_for(:controller => 'sessions', :action => 'connect', :only_path => false, :protocol => 'http')
	logintext = "Ingresar"
# Otherwise continue to next step
else			
	loginlink = "javascript:logout()"
	logintext = "Salir"
end
%>
<!DOCTYPE html>
<html>
<head>
	<%= csrf_meta_tags %>
	<meta charset="utf-8" />
	<title><%= @title %></title>

	<link type="text/css" rel='stylesheet' href='http://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic' />	
	<link type="text/css" rel="stylesheet" href="/css/default.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox.css?v=2.0.5" /> 

	<script type="text/javascript" src="/js/jquery.latest.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/js/jquery.pngFix.pack.js"></script>
	<script type="text/javascript">
	$.ajaxSetup({ 
		'beforeSend': function(xhr) { xhr.setRequestHeader("Accept", "text/javascript"); }
	});
	$.ajaxSetup({
		'beforeSend': function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $("meta[name='csrf-token']").attr('content')); }
	});

	$(function() {
	   $.support.placeholder = false;
	   test = document.createElement('input');
	   if('placeholder' in test) $.support.placeholder = true;
	});
	</script>

	<script type="text/javascript" src="/js/html5/modernizr-1.6.min.js"></script>
	<script type="text/javascript" src="/js/html5/EventHelpers.js"></script>
	<script type="text/javascript" src="/js/html5/html5Widgets.js"></script>

	<!--[if IE]>
	<script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<script type="text/javascript" src="/js/cufon/cufon-yui.js"></script>
	<script type="text/javascript" src="/js/cufon/Lavanderia_420.font.js"></script>
	<script type="text/javascript" src="/js/cufon/ChunkFive_400.font.js"></script>
	<script type="text/javascript" src="/js/jquery.ui.touch-punch.min.js"></script>
	<script type="text/javascript" src="/js/jscrollpane/jquery.mousewheel.js"></script>
			
	<script type="text/javascript" src="/js/jquery-scrolltofixed-min.js"></script>		
	<script type="text/javascript" src="/js/fancybox/jquery.fancybox.pack.js?v=2.0.5"></script>

	<% if session[:bread] %>
		<% if session[:bread].last.first == "Completar formulario" %>
		<script type="text/javascript" src="/js/jquery.validate.js"></script>
		<% end %>
	
		<% if session[:bread].last.first == "Seleccionar Fotos" %>
		<script type="text/javascript" src="/js/jquery.offtmp.js"></script>	
		<% end %>
	<% end %>
	
	<% 
	if !session[:abread].nil?
		if session[:abread].last.last == editadmin_path 
	%>
		<script type="text/javascript" src="/js/jquery.validate.js"></script>		
	<%
		end
	end
	%>

	<script type="text/javascript" src="/js/app.js"></script>
	<script type="text/javascript" src="/js/admin.js"></script>

	<script type="text/javascript">
	// Cufon	
	Cufon.replace('header h1', {fontFamily: 'ChunkFive'});
	Cufon.replace('h2', {fontFamily: 'Lavanderia'}); // Works without a selector engine
	Cufon.replace('.tagline', {fontFamily: 'Lavanderia'}); // Requires a selector engine for IE 6-7, see above	

	$(document).ready(function() {
		hover_links('a.hoverbutton');
		$(".sampledata a").fancybox();				
		scrollToFixed();
		check_promocode();

		$(".loginbutton").hover(
			function() { $(this).attr("src","/images/loginbutton-hover.png"); },
			function() { $(this).attr("src","/images/loginbutton.png");  
		}).animate("slow");

		<% if session[:bread] %>
		<% if session[:bread].last.first == "Seleccionar Fotos" %>
		select_toogle();
		<% end %>
		
		<% case session[:s] %>
		<% when "3" then %>
		var max = 128;
		<% when "2" then %>
		var max = 252;
		<% else %>
		var max = 20;
		<% end %>
			
		delete countchecked;
		imageSelector();
		validate_imageboxes(max);
	<% end %>
		
	<% if session[:bread] %>
		<% if session[:bread].last.first == "Completar formulario" %>
		validate_orderform();
		<% end %>
	<% end %>
	});	

	function logout() {
		$.ajax({
			type: "POST",
			dataType: "json",
			url: "http://instagram.com/accounts/logout/",
			success: window.location.href = "<%= url_for(:controller => 'sessions', :action => 'logout') %>"
		});
	}
	</script>	
	
	<meta name="robots" content="index,follow" />
	<meta name="keywords" content="fotos instagram, imprimir fotos instagram, instagram impresión de fotos, impresión de fotos instagram, como imprimir fotos instagram, donde imprimir fotos instagram, imprimir fotos de instagram en chile, impresión fotos instagram chile, instaprinter chile, instaprinter impresión de fotos instagram, imanes de instagram fotoiman, imprimir imanes, imanes barato, imprimir poster instagram, imprimir stickers de instagram" />
	<meta name="description" content="Instaprinter. Impresión de fotos Instagram. Imprima las fotos de Instagram en nuestro servicio y te las llevamos a tu casa!" />
	<meta name="copyright" content="&copy; InstaPrinter. By Lipresso Networks" />
	<meta name="msvalidate.01" content="E1EA97EFFF3AEAAA5F0800028FD821B5" />
	
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-32159931-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
</head>
<body>
<div class="beta">
	<img src="/images/beta.png" width="90" height="90" alt="Instaprinter Beta" />
</div>
<div class="topwrapper">
</div>
<nav>
	<%
	if !session[:access_token]
		login_href = url_for(:controller => 'sessions', :action => 'connect', :only_path => false, :protocol => 'http')
		login_link_title = "Ingresar"
	else			
		login_href = "javascript:logout();"
		login_link_title = "Salir"
	end	
	%>
	<a id="home" href="<%= root_path %>"><img src="/images/home.png" alt="Principal" /> Home</a>
	<strong>|</strong> <a id="contacts" href="/contacts">Contactos</a>
	<% if !session[:access_token] %>
	<strong>|</strong> <a href="#">Carrito de compras</a>
	<% else %>
	<strong>|</strong> <a class="shoppingcart" href="/basket">Carrito de compras (<span class="scsum"><%= session[:scsum] %></span>)</a>
	<% end %>
	<strong>|</strong> <a class="singin" href="<%= login_href %>"><%= login_link_title %></a>
</nav>

<%= yield %>

<footer>
	<p>&copy; 2012, Instaprinter. <a href="/contacts">Contactos</a> | Creado en <a href="http://www.lipresso.com">Lipresso Networks</a></p>
</footer>
<script type="text/javascript"> 
	Cufon.now();
</script>
</body>
</html>

app/views/pages/contacts.html.erb
<header>		
	<h1>Contactanos</h1>
</header>

<section id="content" class="widecolumn clearfix">
	<section id="breadcrumbs" class="generic">
		<%= render 'layouts/breadcrumbs' %>
	</section><!--#breadcrumps-->

	<div class="commontypo">

	<p>Instaprinter esta abierto a comunicación.<br/> Cualquier duda, consulta o sugerencia estamos a su disposicíón.<br/> Contactanos por correo electrónico al</p>
	<p><a href="mailto:mail@instaprinter.cl?subject=Feedback Instaprinter">mail@instaprinter.cl</a></p>

	<p>Encuentranos en redes sociales:</p>
	
	<p class="center"><a class="hoverbutton" href="http://www.facebook.com/instaprinterchile"><img src="/images/facebook.png" alt="Instaprinter en Facebook" /></a> <a class="hoverbutton" href="http://www.twitter.com/CLInstaprinter"><img src="/images/twitter.png" alt="Twitter Instaprinter" /></a> <a class="hoverbutton" href="https://plus.google.com/101872613415716010246/posts"><img src="/images/googleplus.png" alt="Google+ Instaprinter" /></a></p>
	
	</div>

	<div class="clear"></div>	
</section><!--#content-->